http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  product:
    host: localhost
    paths: '/product'
  order:
    host: localhost
    paths: '/order'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  productService:
    url: 'http://localhost:3000'
  orderService:
    url: 'http://localhost:3002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  productPipeline:
    apiEndpoints:
      - product
    policies:
      - cors:
          enabled: true
          origins: '*'
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
      - cors:
          enabled: true
          origins: '*'
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
